//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PrtSys.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PRTSYSTYPE                  129
#define IDC_MAGNIFI                     131
#define IDC_WHEEL                       132
#define IDC_ROT                         133
#define IDD_3dsCtrlDlg                  135
#define IDD_DLG_Fire                    136
#define IDB_FIRE_1                      139
#define IDD_DLG_COLOR                   140
#define IDD_SCREEN                      141
#define IDD_DLG_WaterFall               142
#define IDD_DLG_FireWork                143
#define IDD_DLG_AtomicBomb              144
#define IDD_DLG_Snow                    145
#define IDD_DLG_RAIN                    146
#define IDB_FIRE_2                      150
#define IDB_FIRE_3                      151
#define IDB_FIRE_4                      152
#define IDB_LJX                         153
#define IDB_XJ                          154
#define IDB_SNOW                        155
#define IDB_RAIN_1                      156
#define IDB_RAIN_X                      157
#define IDB_WF_1                        158
#define IDB_WF_3                        159
#define IDB_WF_2                        160
#define IDD_DLG_BMP                     161
#define IDC_POS_X                       1002
#define IDC_POS_Y                       1003
#define IDC_POS_Z                       1004
#define IDC_ROT_X                       1005
#define IDC_ROT_Y                       1006
#define IDC_ROT_Z                       1007
#define IDC_SCALE                       1008
#define IDC_SLD_MAXNUM                  1011
#define IDC_E_MAXNUM                    1012
#define IDC_SLD_LIFEFATE                1013
#define IDC_E_LIFEFATE                  1014
#define IDC_SLD_SLOWDOWN                1015
#define IDC_E_SLOWDOWN                  1016
#define IDC_SLD_SPEEDMAX                1017
#define IDC_E_SPEEDMAX                  1018
#define IDC_SLD_SPEEDMIN                1019
#define IDC_E_SPEEDMIN                  1020
#define IDC_SLD_ALYSTAR                 1021
#define IDC_SW_ALYEND                   1021
#define IDC_E_ALYSTAR                   1022
#define IDC_SW_ALXZSTAR                 1022
#define IDC_SLD_ALYEND                  1023
#define IDC_SW_ALXZEND                  1023
#define IDC_E_ALYEND                    1024
#define IDC_SLD_ALXZSTAR                1025
#define IDC_SW_GETX                     1025
#define IDC_E_ALXZSTAR                  1026
#define IDC_SLD_ALXZEND                 1027
#define IDC_SW_GETY                     1027
#define IDC_E_ALXZEND                   1028
#define IDC_SLD_GETX                    1029
#define IDC_SW_GETZ                     1029
#define IDC_E_GETX                      1030
#define IDC_SLD_GETY                    1031
#define IDC_E_GETY                      1032
#define IDC_SLD_GETZ                    1033
#define IDC_E_GETZ                      1034
#define IDC_S_TextWitdh                 1035
#define IDC_E_POS_X                     1036
#define IDC_E_POS_Y                     1037
#define IDC_E_POS_Z                     1038
#define IDC_E_TextWidth                 1040
#define IDC_R_F1                        1041
#define IDC_R_F2                        1042
#define IDC_R_F3                        1043
#define IDC_R_F4                        1044
#define IDC_B_Color                     1045
#define IDC_R1                          1046
#define IDC_G1                          1047
#define IDC_B1                          1048
#define IDC_R2                          1049
#define IDC_BE1                         1050
#define IDC_G2                          1051
#define IDC_B2                          1052
#define IDC_BE2                         1053
#define IDC_R3                          1054
#define IDC_G3                          1055
#define IDC_B3                          1056
#define IDC_BE3                         1057
#define IDC_R4                          1058
#define IDC_G4                          1059
#define IDC_B4                          1060
#define IDC_BE4                         1061
#define IDC_R5                          1062
#define IDC_G5                          1063
#define IDC_B5                          1064
#define IDC_BE5                         1065
#define IDC_E_Title                     1066
#define IDC_R_64                        1067
#define IDC_R_86                        1068
#define IDC_R_17                        1069
#define IDC_EW_POS_X                    1070
#define IDC_EW_POS_Y                    1071
#define IDC_EW_POS_Z                    1072
#define IDC_SW_MAXNUM                   1073
#define IDC_SW_LIFEFATE                 1074
#define IDC_SW_SLOWDOWN                 1075
#define IDC_SW_SPEEDMAX                 1076
#define IDC_SW_SPEEDMIN                 1077
#define IDC_EW_MAXNUM                   1078
#define IDC_EW_LIFEFATE                 1079
#define IDC_EW_SLOWDOWN                 1080
#define IDC_EW_SPEEDMAX                 1081
#define IDC_EW_SPEEDMIN                 1082
#define IDC_EW_ALYEND                   1083
#define IDC_EW_ALXZSTAR                 1084
#define IDC_EW_ALXZEND                  1085
#define IDC_EW_GETX                     1086
#define IDC_EW_GETY                     1087
#define IDC_EW_GETZ                     1088
#define IDC_EW_PPX                      1090
#define IDC_BW_COLOR                    1091
#define IDC_SW_TextWidth                1092
#define IDC_EW_TextWidth                1093
#define IDC_RW_1                        1094
#define IDC_RW_2                        1095
#define IDC_EI_POS_X                    1095
#define IDC_RW_3                        1096
#define IDC_EI_POS_Y                    1096
#define IDC_EI_POS_Z                    1097
#define IDC_SI_MAXNUM                   1098
#define IDC_EI_MAXNUM                   1099
#define IDC_SI_LIFEFATE                 1100
#define IDC_EI_LIFEFATE                 1101
#define IDC_SI_SLOWDOWN                 1102
#define IDC_EI_SLOWDOWN                 1103
#define IDC_SI_SPEEDMAX                 1104
#define IDC_EI_SPEEDMAX                 1105
#define IDC_SI_SPEED_MIN                1106
#define IDC_EI_SPEEDMIN                 1107
#define IDC_SI_ALYSTAR                  1108
#define IDC_EI_ALYSTAR                  1109
#define IDC_SI_ALYEND                   1110
#define IDC_EI_ALYEND                   1111
#define IDC_SI_ALXZSTAR                 1112
#define IDC_EI_ALXZSTAR                 1113
#define IDC_SI_ALXZEND                  1114
#define IDC_EI_ALXZEND                  1115
#define IDC_SI_GETX                     1116
#define IDC_EI_GETX                     1117
#define IDC_SI_GETY                     1118
#define IDC_EI_GETY                     1119
#define IDC_SI_GETZ                     1120
#define IDC_EI_GETZ                     1121
#define IDC_RI_1                        1122
#define IDC_BI_COLOR                    1123
#define IDC_EA_POS_X                    1124
#define IDC_EA_POS_Y                    1125
#define IDC_EA_POS_Z                    1126
#define IDC_SA_MAXNUM                   1127
#define IDC_SIS_MAXNUM                  1128
#define IDC_EA_MAXNUM                   1128
#define IDC_EIS_MAXNUM                  1129
#define IDC_SIS_LIFEFATE                1130
#define IDC_ES_POS_X                    1130
#define IDC_EIS_LIFEFATE                1131
#define IDC_ES_POS_Y                    1131
#define IDC_SIS_SLOWDOWN                1132
#define IDC_ES_POS_Z                    1132
#define IDC_EIS_SLOWDOWN                1133
#define IDC_SS_MAXNUM                   1133
#define IDC_SIS_SPEEDMAX                1134
#define IDC_ES_MAXNUM                   1134
#define IDC_EIS_SPEEDMAX                1135
#define IDC_SS_SLOWDOWN                 1135
#define IDC_SIS_SPEEDMIN                1136
#define IDC_ES_SLOWDOWN                 1136
#define IDC_EIS_SPEEDMIN                1137
#define IDC_SS_ALXZSTAR                 1137
#define IDC_SIS_GETX                    1138
#define IDC_ES_ALXZSTAR                 1138
#define IDC_EIS_GETX                    1139
#define IDC_SS_ALXZEND                  1139
#define IDC_SIS_GETY                    1140
#define IDC_ES_ALXZEND                  1140
#define IDC_EIS_GETY                    1141
#define IDC_SS_LIFEFATE                 1141
#define IDC_SIS_GETZ                    1142
#define IDC_ES_LIFEFATE                 1142
#define IDC_EIS_GETZ                    1143
#define IDC_SS_PRAM0                    1143
#define IDC_SI_TextWidth                1144
#define IDC_ES_PRAM0                    1144
#define IDC_EI_TextWidth                1145
#define IDC_SS_ALYSTAR                  1145
#define IDC_RI_2                        1146
#define IDC_ES_ALYSTAR                  1146
#define IDC_RI_3                        1147
#define IDC_SS_ALYEND                   1147
#define IDC_RI_4                        1148
#define IDC_ES_ALYEND                   1148
#define IDC_SS_SPEEDMAX                 1149
#define IDC_ES_SPEEDMAX                 1150
#define IDC_SS_SPEEDMIN                 1151
#define IDC_ES_SPEEDMIN                 1152
#define IDC_SS_GETX                     1153
#define IDC_ES_GETX                     1154
#define IDC_SS_GETY                     1155
#define IDC_ES_GETY                     1156
#define IDC_SS_GETZ                     1157
#define IDC_ES_GETZ                     1158
#define IDC_SS_TextWidth                1159
#define IDC_ES_TextWidth                1160
#define IDC_SS_ALPHA                    1161
#define IDC_ES_ALPHA                    1162
#define IDC_RS1                         1163
#define IDC_RS2                         1164
#define IDC_RS3                         1165
#define IDC_RS4                         1166
#define IDC_ES_C_R                      1167
#define IDC_ES_C_G                      1168
#define IDC_ES_C_B                      1169
#define IDC_BS_COLOR                    1170
#define IDC_ER_POS_X                    1171
#define IDC_ER_POS_Y                    1172
#define IDC_ER_POS_Z                    1173
#define IDC_SR_MAXNUM                   1174
#define IDC_ER_MAXNUM                   1175
#define IDC_SR_LIFEFATE                 1176
#define IDC_ER_LIFEFATE                 1177
#define IDC_SR_SLOWDOWN                 1178
#define IDC_ER_SLOWDOWN                 1179
#define IDC_SR_SPEEDMAX                 1180
#define IDC_ER_SPEEDMAX                 1181
#define IDC_SR_SPEEDMIN                 1182
#define IDC_ER_SPEEDMIN                 1183
#define IDC_SR_ALXZSTAR                 1184
#define IDC_ER_ALXZSTAR                 1185
#define IDC_SR_ALXZEND                  1186
#define IDC_ER_ALXZEND                  1187
#define IDC_SR_GETX                     1188
#define IDC_ER_GETX                     1189
#define IDC_SR_GETY                     1190
#define IDC_ER_GETY                     1191
#define IDC_SR_GETZ                     1192
#define IDC_ER_GETZ                     1193
#define IDC_SR_TextWidth                1194
#define IDC_ER_TextWidth                1195
#define IDC_SR_ALPHA                    1196
#define IDC_ER_ALPHA                    1197
#define IDC_ER_CR                       1199
#define IDC_ER_CG                       1200
#define IDC_ER_CB                       1201
#define IDC_BR_COLOR                    1202
#define IDC_R_R1                        1206
#define IDC_R_R2                        1207
#define IDC_BF_LOAD                     1208
#define IDC_BF_SAVE                     1209
#define IDC_BFW_LOAD                    1210
#define IDC_BFW_SAVE                    1211
#define IDC_BR_LOAD                     1212
#define IDC_BR_SAVE                     1213
#define IDC_BS_LOAD                     1213
#define IDC_BS_SAVE                     1214
#define IDC_BW_LOAD                     1214
#define IDC_BW_SAVE                     1215
#define IDC_EB_FILE                     1216
#define IDC_BB_FILE                     1217
#define IDC_BB_LOAD                     1218
#define IDC_BB_SAVE                     1219
#define IDC_EB_POS_X                    1221
#define IDC_EB_POS_Y                    1222
#define IDC_EB_POS_Z                    1223
#define IDC_SB_MAXNUM                   1224
#define IDC_SB_LIFEFATE                 1225
#define IDC_SB_SLOWDOWN                 1226
#define IDC_EB_LIFEFATE                 1227
#define IDC_EB_SLOWDOWN                 1228
#define IDC_SB_GETX                     1229
#define IDC_SB_GETY                     1230
#define IDC_SB_GETZ                     1231
#define IDC_SB_TextWitdh                1232
#define IDC_EB_GETX                     1233
#define IDC_EB_GETY                     1234
#define IDC_EB_GETZ                     1235
#define IDC_EB_TextWidth                1236
#define IDC_SB_Thick                    1237
#define IDC_EB_Thick                    1238
#define IDC_EB_MAXNUM                   1239
#define IDC_BS_EQUAL                    1240
#define IDC_RS5                         1241
#define IDC_RS6                         1242
#define ID_FULLSCREEN                   32772
#define ID_KW_FULLSCREEN                32774
#define ID_KW_FACEORLINE                32775
#define ID_HIDEORSHOW                   32778
#define ID_SHOW3DSDLG                   32779
#define ID_KW_HIDEORSHOW                32780
#define ID_KW_SHOW3DSDLG                32781
#define ID_KW_PLAY                      32782
#define ID_SHOW_FIRE                    32783
#define ID_KW_SETFULLSCREEN             32784
#define ID_KW_SHOWWATERFALL             32785
#define ID_SHOW_WATERFALL               32786
#define ID_SHOW_FIREWORK                32787
#define ID_EDIT_FIRE                    32788
#define ID_EDIT_WATERFALL               32789
#define ID_EDIT_FIREWORK                32790
#define ID_MENUITEM32791                32791
#define ID_SHOW_ATOMICBOMB              32792
#define ID_EDIT_ATOMICBOMB              32793
#define ID_MENUITEM32794                32794
#define ID_SHOW_SNOW                    32795
#define ID_MENUITEM32796                32796
#define ID_EDIT_SNOW                    32797
#define ID_MENUITEM32798                32798
#define ID_SHOW_RAIN                    32799
#define ID_MENUITEM32800                32800
#define ID_EDIT_RAIN                    32801
#define ID_KW_DEMO                      32802
#define ID_KW_CROSS                     32803
#define ID_KW_FILEOPEN                  32804
#define M_1111                          32805
#define ID_MENUITEM32806                32806
#define ID_SHOW_BMP                     32807
#define ID_EDIT_BMP                     32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1243
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
